kantord/LibreLingo

- docs/attributions.md
- docs/index.md
Currently, they're being rendered as text.
> docs: Update links to render them as links in readthedocs

- package.json
- src/mystyles.scss
- src/routes/_layout.svelte
- yarn.lock
This adds a pageloader which is rendered only on the server side, therefore the user will see it
until the first full client-side render
fixes #183
> feat: add pageloader

- src/components/InputFieldWithVirtualKeyboard.svelte
Adds the `autocapitalize="none"` attribute to the input field.
Commit tested on iOS 13.3
> Fixes #247: autocapitalize issue on iOS 

- workspaces/web/src/components/ChipsChallenge.svelte
This should fix https://github.com/kantord/LibreLingo/issues/341
It basically adds the same section for binding the enter key as in other files, like `ShortInputChallenge.svelte`. Both continuing and submitting now work for me (Firefox 79.0, Arch Linux).
Sorry if I've oversaw something and `onMount` is not called there for a reason. Also sorry if I violated some code guidelines - svelte is new to me. Making a pull request on github as well, but this project looks pretty cool, so I thought I should contribute somehow :)
> fix: fix enter key in ChipsChallenge

- workspaces/lluis/Button.svelte
- workspaces/web/src/components/InputFieldWithVirtualKeyboard.svelte
Lowercase typography was broken, because an all-caps font was forced. This doesn't work well for the
virtual keyboard, hence I fixed it
fixes #579
> fix(button): fix lowercase typography on the virtual keyboard

- docs/index.md
This adds the `exportcouse` command mentioned in [an issue](https://github.com/kantord/LibreLingo/issues/227#issuecomment-678769336) to the documentation, so it can be found easier.
This fixes #625.
> Documenting the exportcourse command

- workspaces/web/src/components/MarkDownPage.svelte
- workspaces/web/src/routes/about.svelte
- workspaces/web/src/routes/development.svelte
- workspaces/web/src/routes/index.svelte
- workspaces/web/src/routes/sign-up-success.svelte
- workspaces/web/src/routes/sign-up.svelte
- workspaces/web/src/translation/en.json
Add meta description to the head of the index, about, development and sign-up pages.
Fixes #185
> feat: add meta descriptions

- workspaces/web/src/routes/development.svelte
> docs: remove 'want to help naming mascot?' from the development page

- courses/bangla-from-english/basics/module.yaml
- courses/bangla-from-english/basics/skills/animals.yaml
- courses/bangla-from-english/basics/skills/clothes.yaml
- courses/bangla-from-english/basics/skills/food.yaml
- courses/bangla-from-english/basics/skills/nature.yaml
- courses/bangla-from-english/basics/skills/plurals.yaml
- courses/bangla-from-english/basics/skills/professions.yaml
- courses/bangla-from-english/basics/skills/verb_plurals.yaml
- courses/bangla-from-english/basics/skills/verbs.yaml
- courses/bangla-from-english/course.yaml
Adds "basics" course for Bangla (aka Bengali) language. Bangla is the 7th most spoken language according to [Ethnologue (2020)](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers#Ethnologue_(2020,_23rd_edition)). So hope it's useful for the project and the users.
No
I've just created the basics course for Bangla. Plan to add the rest of them similar to the Spanish course. Created this PR to see if I'm on the right track before continuing. Please let me know if I need to add/change anything.
> Add Bangla course

- docs/courses/README.md
- docs/courses/course.md
- docs/courses/creating-courses.md
- docs/courses/editing-courses.md
- docs/courses/module.md
- docs/courses/skill.md
Makes the courses docs beginner friendly and more reference-able.
related to issue #1145
1. Not sure if a better wording for "target audience's language" should be used. e.g.
**`Mini-dictionary`**
- `<destination language>`: A list of words in destination language as key and meaning in target audience's language.
2. The content before was hard wrapped to 80 chars per line. But I didn't do it for my changes. Is it important?
3. There are TODOs in places. e.g. `[TODO: Explain where and how it is used]`
4. I've created separate files for course, module and skill so that they can be referenced from any page on the docs, or even be used as a developer reference or can even be linked on a …
> docs: make courses docs beginner friendly

- .semaphore/pipeline_2.yml
This should fix the failing pipeline for the librelingo-standalone-server builds. I forgot to modifiy the path in the pipeline configuration before, sorry.
fixes #1175
> fix: correct path for the binary building pipeline

- README.md
Little aesthetics for the readme :grin:
Basically, the matrix.to service allows the user to choose which matrix client to open, whereas riot.im just opens the web app for Element (formerly riot).
> chore(docs): Link to chat via matrix.to, instead of riot.im

- apps/librelingo_json_export/librelingo_json_export/challenge_types.py
- apps/librelingo_json_export/librelingo_json_export/cli.py
- apps/librelingo_json_export/tests/snapshots/snap_test_integration.py
- apps/librelingo_json_export/tests/test_cli.py
- apps/librelingo_json_export/tests/test_export.py
- apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader.py
- poetry.lock
- pyproject.toml
> chore: set up mypy

- apps/web/src/courses/french-from-english/challenges/hello.json
- apps/web/src/courses/german-from-english/challenges/hello.json
- apps/web/src/courses/parsig-from-english/challenges/basic-1.json
- courses/french-from-english/basics/skills/hello.yaml
- courses/german-from-english/basics/skills/hello.yaml
- courses/parsig-from-english/basics/skills/hello.yaml
I believe this line https://github.com/kantord/LibreLingo/blob/d1d2a57082534833c49ad378cd8e831cfce9cafa/apps/web/src/components/ChallengeScreen.svelte#L89
results in an error for french, parsig & german languages because "woman" has no image associated with it in. So I added a pictures array in the json and references to the images in the yaml files
fixes #1315 
**Screenshots**
Before update (tested with german, parsig & french): 
After update (tested with german, parsig & french):
(only one image seems to load for cards but it's no longer responding with an error. I think this is because there aren't enough cards in the challenge)
Don't worry if you haven't done everything on this checklist. Simply create your PR, and make sure everything is done …
> Add missing images for woman in french, german & parsig

- docs/index.md
Not sure if these are helpful, but here's some documentation of additional steps I found on the way to setting up a development environment.
> Notes from setting up my development environment

- apps/web/src/courses/test/challenges/cards-test.json
- apps/web/src/courses/test/courseData.json
- apps/web/src/logic.js
- courses/test/basics/skills/_cards_test.yaml
Prevents the user from seeing multiple copies of the same option in an options challenge.
> fix: do not display multiple of the same option in options challenges

- apps/web/cypress/integration/chips.feature
- apps/web/src/components/ChipsChallenge/index.svelte
- apps/web/src/courses/test/challenges/chips-test-0.json
- courses/test/basics/skills/chips-test-0.yaml
As mentioned [here](https://github.com/kantord/LibreLingo/issues/1445#issuecomment-890482465), requiring correct capitalization for chips challenge solutions is not intended. This change implements that, so that "como pan" is correct if there is an alternative solution "Como pan".
> fix: Accept solutions to chips challenges regardless of case

- apps/web/src/routes/about.svelte
This removes accessing the 'content' string from about as the content string is what now gets returned from 'MarkDownPage'
fixes #1484
No
> fix: About page results in "Error: 500"

- courses/test/course.yaml
Enables audio setting on test course. This is so when we run `yarn exportAllCourses` it doesn't result in a diff. 
Prerequisite for https://github.com/kantord/LibreLingo/pull/1610. 
> fix: Enable audio settings test course

- apps/librelingo_json_export/poetry.lock
- apps/librelingo_json_export/pyproject.toml
This commit fixes the following error when trying to export a
course:
> ./scripts/exportYamlCourse.sh spanish-from-english
> ⏳ Exporting course spanish-from-englishTraceback (most recent call last):
>  File "librelingo_json_export/cli.py", line 5, in <module>
>    from librelingo_json_export.export import export_course
> ModuleNotFoundError: No module named 'librelingo_json_export'
_..._
or ask for help if you don't know how to do …
> fix: Add missing poetry dependency

- apps/librelingo_yaml_loader/poetry.lock
- apps/librelingo_yaml_loader/pyproject.toml
Packages slugify and python-slugify are not used, they can be removed from the dependency list.
> Remove redundant dependencies

- .gitignore
When someone develop a course it will show up in these two directories
and we would like to ignore them. We cannot gitignore the whole
directories /apps/web/src/courses/ and /courses/ because we have the
"test" directory in both.
We can assume that every course will have a dash in its name so
we ignore those.
_..._
> gitignore every course except "test"

- apps/librelingo_audios/tests/test_update_audios.py
- pylintrc
Fixes issue #1900. Removed "consider-using-from-import" from pylintrc and corrected the code accordingly.
fixes #1900 
_..._
> Remove consider using from import

- apps/librelingo_json_export/tests/test_challenges.py
- apps/librelingo_json_export/tests/test_challenges_get_challenges_data.py
The first step in rewriting all of the tests using pytest. I have the moved the methods of the the class [`TestGetChallengesData`](https://github.com/kantord/LibreLingo/blob/fdc63c4a4b1fad8ca16672f3db7c7ab8d87114c8/apps/librelingo_json_export/tests/test_challenges.py#L18) to a new file [`test_challenges_get_challenges_data.py`](https://github.com/vil02/LibreLingo/blob/unittest_to_pytest/apps/librelingo_json_export/tests/test_challenges_get_challenges_data.py).
_..._
> refactor(tests): add test_challenges_get_challenges_data.py

- apps/librelingo_json_export/tests/test_challenges.py
- apps/librelingo_json_export/tests/test_challenges_get_challenges_data.py
- apps/librelingo_json_export/tests/test_challenges_get_phrase_challenges.py
- apps/librelingo_json_export/tests/test_challenges_get_word_challenges.py
Continuation of rewriting all of the tests using pytest.
- I split [`mocks`](https://github.com/kantord/LibreLingo/blob/3ab2cc73c4ec0c76d27ce3e04ba20dbaa4510c12/apps/librelingo_json_export/tests/test_challenges_get_challenges_data.py#L8) into [`mock_get_phrase_challenges`](https://github.com/vil02/LibreLingo/blob/13ac8ffc95e91241e6c85b7128721e738c937764/apps/librelingo_json_export/tests/test_challenges_get_challenges_data.py#L8) and [`mock_get_word_challenges`](https://github.com/vil02/LibreLingo/blob/13ac8ffc95e91241e6c85b7128721e738c937764/apps/librelingo_json_export/tests/test_challenges_get_challenges_data.py#L13),
- I moved the methods of the class [`TestGetWordChallenges`](https://github.com/kantord/LibreLingo/blob/3ab2cc73c4ec0c76d27ce3e04ba20dbaa4510c12/apps/librelingo_json_export/ …
> refactor(tests): split mocks

- apps/librelingo_audios/librelingo_audios/cli.py
- apps/librelingo_audios/librelingo_audios/functions.py
- apps/librelingo_audios/librelingo_audios/update_audios.py
- apps/librelingo_json_export/README.md
- apps/librelingo_json_export/librelingo_json_export/challenge_types.py
- apps/librelingo_json_export/librelingo_json_export/challenges.py
- apps/librelingo_json_export/librelingo_json_export/cli.py
- apps/librelingo_json_export/librelingo_json_export/course.py
- apps/librelingo_json_export/librelingo_json_export/dictionary.py
- apps/librelingo_json_export/librelingo_json_export/export.py
- apps/librelingo_json_export/librelingo_json_export/skills.py
- apps/librelingo_types/README.md
- apps/librelingo_types/librelingo_types/data_types.py
- apps/librelingo_utils/README.md
- apps/librelingo_utils/librelingo_utils/utils.py
- apps/librelingo_yaml_loader/README.md
- apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
- rename variables with "x, c, p" names into more readable variables
- type all possibles methods input/outputs 
- remove unused
_..._
> refactor(codebase): type all possible instances

- package.json
This way, a new cypress config cannot be accidentally created by running
```bash
yarn cypress open
```
also, it's a shortcut :smile_cat:
> chore: alias 'yarn web cypress' as 'yarn cypress'

- apps/librelingo_fakes/librelingo_fakes/fakes.py
I applied the function [`fakes.number`](https://github.com/LibreLingo/LibreLingo/blob/f866381521f2e118f2ec3a0b12cba94316261a7b/apps/librelingo_fakes/librelingo_fakes/fakes.py#L270) in [`fakes.path`](https://github.com/LibreLingo/LibreLingo/blob/f866381521f2e118f2ec3a0b12cba94316261a7b/apps/librelingo_fakes/librelingo_fakes/fakes.py#L289).
This has been [already](https://github.com/LibreLingo/LibreLingo/pull/1955/commits/930254162b53ed264acf58d80c5ae6745030d6b8) done, but I think it was lost while some merge conflict resolving.
> refactor: use number(5000) in path()

- pylintrc
removed trailing pylint commented rule
> chore(pylint): remove trailing unused-argument commented pylint rule

- apps/librelingo_audios/tests/test_update_audios.py
- apps/librelingo_json_export/tests/test_cli.py
- apps/librelingo_json_export/tests/test_export_course.py
- apps/librelingo_json_export/tests/test_export_course_data.py
- apps/librelingo_json_export/tests/test_export_course_skills.py
- apps/librelingo_json_export/tests/test_export_skill.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader_convert_phrases.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader_convert_words.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader_load_skills.py
Continuation of [rewriting all of the tests using `pytest`](https://github.com/kantord/LibreLingo/pull/1912#issuecomment-1002282919).
- I moved the tests from the class [`TestLoadSkills`](https://github.com/LibreLingo/LibreLingo/blob/ec8fedc05700869143312cf2cee3e74a263c88b6/apps/librelingo_yaml_loader/tests/test_yaml_loader.py#L533) to the file [`test_yaml_loader_load_skills.py`](https://github.com/vil02/LibreLingo/blob/eff53f9f9d61457f3a801677d38149d745d1013e/apps/librelingo_yaml_loader/tests/test_yaml_loader_load_skills.py),
- I removed suppression of the `pylint` warnings `unused-argument` and `invalid-name` (cf. #2043 and https://github.com/LibreLingo/LibreLingo/pull/2042#discussion_r804458049)
> refactor(tests): add test_yaml_loader_load_skills.py

- apps/librelingo_yaml_loader/tests/test_yaml_loader.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader_load_modules.py
Continuation of [rewriting all of the tests using `pytest`](https://github.com/kantord/LibreLingo/pull/1912#issuecomment-1002282919).
I moved the tests from the class [`LoadModulesTestCase`](https://github.com/LibreLingo/LibreLingo/blob/de283649c8e8722aea20407682f2c5fa5169704a/apps/librelingo_yaml_loader/tests/test_yaml_loader.py#L509) to the file [test_yaml_loader_load_modules.py](https://github.com/vil02/LibreLingo/blob/6783c3ed38dc3d2aec7e3bafbd31e0da554624a5/apps/librelingo_yaml_loader/tests/test_yaml_loader_load_modules.py).
> refactor(tests): add test_yaml_loader_load_modules.py

- Makefile
This PR is here to open a few discussions concerning some points i was thinking of (yes i just had some extra time haha)
But can we get rid of those `git ls-files '*.py'` from the CI and use some `$(find...)` command, it will not make a big change, but for the next contributors i feel like they will be using this command to simulate the CI whenever it fails, which can lead to some errors on their side (just dev UX), as this command will fail whenever a file is added or removed and is not commited.
A second point, is to have a makefile with useful commands, also a help command that will generate the documentation of those commands, with the pushed makefile we have something similar to:
that is pretty useful for users not used for the codebase (and it's useful just to find quickly the …
> add makefile with a few commands

- apps/lluis/HorizontalScroller.svelte
After a certain number of characters, the virtual keyboard would cut off on the second row.
This appears (thus far) to only occur for the French course, as there are not enough characters in the others.
This pull request adjusts the `position` property of the keyboard from `absolute` to `relative`.
This allows the entire keyboard to be seen instead of only partly seen.
This is my first pull request, so let me know if there's anything I can do better!
Resolves #2442
> Fix virtual keyboard being cut in half for audio task

- .github/workflows/python.yml
I added `macos-11` to [python workflow](https://github.com/LibreLingo/LibreLingo/blob/a012439e84ba3ca2661ed4954fb33df79396da2f/.github/workflows/python.yml).
`poetry` is installed using [`snok/install-poetry@v1`](https://github.com/snok/install-poetry) - this will also work on windows. Installing `poetry` in this way, requires `bash` as a shell in every relevant step. I am open here for other suggestions.
This should solve #2479.
@ztjhz please have a look - it might be relevant to #2480.
> chore: add macos-11

- .github/workflows/python.yml
- apps/librelingo_json_export/tests/snapshots/snap_test_integration.py
- apps/librelingo_json_export/tests/test_integration.py
- apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader.py
- apps/tools/tests/test_real_courses.py
- apps/tools/tests/test_test_course.py
This pull request adds windows to the CI of GitHub Actions, while fixing issues prevalent on windows machine.
Solution: set the default shell to `bash` in `python.yml`
```yaml
defaults:
run:
shell: bash
```
Solution: utilise dynamic file paths
Example: change `"./output/challenges/hello.json"` to `str(Path("./output/challenges/hello.json"))`
For the regex matching in `pytest.raises(RuntimeError, match=expected_error)`, the `expected_error` was not escaped. This might cause errors in certain scenarios like windows file separator being `\\` . Hence, we need to escape it first by using `re.escape()`
Not specifying character encoding when reading files, might result in different special characters being read on windows and unicode decode errors.
Solution: specify the encoding:
```python
with …
```
> Python ci windows check

- scripts/exportYamlCourse.sh
By executing the command `yarn exportAllCourses` or equivalency by running `./scripts/exportAllYamlCourses.sh` one gets an output similar to
```
✅ Exported course brazilian-portuguese-from-englishh
✅ Exported course french-from-englishh
✅ Exported course german-from-englishh
✅ Exported course houma-from-englishh
✅ Exported course neolatin-from-englishh
✅ Exported course spanish-from-englishh
✅ Exported course testt
```
Note the duplicated character at the end of each line. This comes form the fact that [_exporting course message_](https://github.com/LibreLingo/LibreLingo/blob/35a0fe190e37a8c72eeb2eb18eb23886a9391388/scripts/exportYamlCourse.sh#L5) is one character longer than [_exporting is done message_](https://github.com/LibreLingo/LibreLingo/blob/35a0fe190e37a8c72eeb2eb18eb23886a939138 …
> style: remove duplicated character

- apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
- apps/librelingo_yaml_loader/tests/test_yaml_loader.py
By making use of CSafeLoader we require that the LibYAML C bindings of PyYAML are installed. If these bindings are not present, this commit ensures that the YAML Loader still works. However, performance will not be as good as with the C bindings.
> Ensure that YAML loader works without PyYAML C bindings

- apps/librelingo_audios/librelingo_audios/update_audios.py
- apps/librelingo_fakes/librelingo_fakes/fakes.py
- apps/tools/tests/test_real_courses.py
- apps/tools/tests/test_test_course.py
- pylintrc
Enabled the "duplicate-code" rule in the pylint config and changed the configuration settings for the rule. Refactored the following files to reduce the amount of duplicate code:
_apps/tools/tests/test_real_courses.py
apps/tools/tests/test_test_course.py_
Import the Settings object from fakes instead of declaring a new one
_apps/librelingo_audios/librelingo_audios/update_audios.py_
Pylint found lines 122-127 to be too similar to lines 73-78 of _conftest.py_. This seems to me to be an acceptable case of duplicate code, given that the lines of _conftest.py_ are used to test those from _update_audios.py_. However, the CI will not pass if they are left as is, so it was necessary to make some change. It seemed sensible to use a variable for TTS provider, given that more providers could be …
> Enable pylint duplicate-code rule

- config/courses.json
As discussed in #2538, add metadata:
- source, e.g., "English"
- target, e.g., "Spanish"
- name, e.g., "spanish-from-english"
- description, e.g., "Spanish for English speakers"
> Add metadata to courses configuration file

- Makefile
[`Makefile`](https://github.com/LibreLingo/LibreLingo/blob/9decb515065e7d99121e26b70a54b706ca77cf91/Makefile) runs commands on all `*.py` files, including the ones in `node_modules`.
This PR excludes `node_modules` from the search and updates the explanation of the [`check-type`](https://github.com/LibreLingo/LibreLingo/blob/9decb515065e7d99121e26b70a54b706ca77cf91/Makefile#L11) command.
> chore: exclude `node_modules` from `PYTHON_FILEPATHS`

- README.md
Fixes #3029 
Changed omnilingo broken Link to its original repository.
> omnilingo broken link in readme

- apps/librelingo_yaml_loader/librelingo_yaml_loader/skill.json
scripts/verifyTestCourseJsonFiles.sh breaks on invalid json
> Fix invalid json in librelingo_yaml_loader
