.gitlab-ci.yml, cypress/integration/coursePage.js, package.json, src/db.js, src/routes/index.svelte, yarn.lock
=> set up couchdb

src/routes/course/[courseName]/index.svelte, src/routes/course/[courseName]/skill/[id].svelte, src/routes/index.svelte
=> Fix page titles #27

cypress/integration/cards.js, src/components/DeckChallenge/logic.js, src/components/OptionDeck.svelte, src/courses/spanish-from-english/challenges/food.json, src/courses/spanish-from-english/courseData.json
=> on mobile, display 4 cards instead of 3 #8

.github/workflows/preview-on-PR.yml, now.json
References issue #74 
@kantord 
In `now.json` change the name to something you like, I tested it on `librelingotest` so as to not block `librelingo`
Also you will need to add your ZEIT_TOKEN secret in the Repository's settings
=> Added build and preview using Zeit Now

course_editor/course/management/commands/exportcourse.py, cypress/integration/listening.js, src/components/ListeningChallenge.svelte, src/courses/spanish-from-english/challenges/animals.json, src/courses/spanish-from-english/challenges/food.json, src/courses/test/challenges/_listening_test0.json
=> Show meaning after successful ListeningChallenge #91

README.md, course_editor/dumps/courseData.json, dump_course_editor_data.sh, src/courses/spanish-from-english/courseData.json
=> Store course editor database dump in repo #86

src/components/ListeningChallenge.svelte
=> Add type to button to prevent it triggering submit (#116)

src/components/ChallengeScreen.svelte
=> Transitions between challenges within a lesson are a bit broken #88

src/mystyles.scss, src/routes/_layout.svelte, src/routes/course/[courseName]/index.svelte, src/template.html
adds a footer with information about the project and various links
fixes #230
=> feat: add footer

.hound.yml, .semaphore/semaphore.yml, cypress/integration/cards.js, cypress/integration/chips.js, cypress/integration/coursePage.js, cypress/integration/fanfareScreen.js, cypress/integration/listening.js, cypress/integration/optionSelection.js, cypress/integration/shortInput.js, cypress/plugins/index.js, cypress/support/commands.js, package.json, yarn.lock
Integrate Percy into Cypress to enable visual regression testing
fixes #236
=> ci: set up Percy for visual regression testing

cypress/integration/cards.js, cypress/integration/chips.js, cypress/integration/coursePage.js, cypress/integration/fanfareScreen.js, cypress/integration/listening.js, cypress/integration/optionSelection.js, cypress/integration/shortInput.js, src/courses/test/challenges/_cards_test.json, src/courses/test/challenges/_chips_test1.json, src/courses/test/challenges/_options_test.json, src/routes/about.svelte, src/routes/course/[courseName]/skill/[id].svelte
Provide unique names for snapshots and make sure tests are consistent visually
fixes #254
=> test: fix percy tests

README.md
Typos in About
it's -> its
controbutors -> contributors
syncronised -> synchronised
=> Fixes Typos described in #388

docs/index.md
Small patch for the starter docs as I'm passing through.
Cool project! :partying_face:
=> Starter docs fixes

workspaces/web/src/components/ChipsChallenge.svelte
=> fix: fix bug with re-ordering chips in chips challenge

workspaces/answer-corrector/index.js, workspaces/answer-corrector/index.test.js
=> fix(answer-corrector): allow for punctuation mistakes, suggest correct form

workspaces/web/src/components/Option.svelte, workspaces/web/src/components/Options.svelte
- Removed duplicate radio button
-  Added styling to make UI consistent
- Tested on Firefox 80.0.1 and Chromium 85.0.4183.102
=> Fix radio select button

workspaces/lluis/package.json, workspaces/web/package.json, yarn.lock
Changes made :
Package | Type | Update | Change
-- | -- | -- | --
bulma (source) | dependencies | minor | 0.8.2 -> 0.9.1
=> fix(deps): update dependency bulma to v0.9.1

workspaces/web/src/components/ChallengePanel.svelte, workspaces/web/src/components/ChallengeScreen.svelte, workspaces/web/src/components/ChipsChallenge/index.svelte, workspaces/web/src/components/DeckChallenge/index.svelte, workspaces/web/src/components/ListeningChallenge.svelte, workspaces/web/src/components/OptionChallenge/index.svelte, workspaces/web/src/components/ShortInputChallenge.svelte
This PR resolves the issue #734 , I follow the issue comments and put as the features below:
- [ X ] Ultimate SKIP (Skipping all remaining challenges);
- [ X ] takes the user back to the course screen;
- [ X ] should appear after the first successful answer;
- [ X ] The button could say sth like Finish early.
I hope that helps. Please, test and let me know if I did something wrong.
Also, can you add the topic "hacktoberfest" on this repository?
Thank you, have a great Hacktoberfest and stay safe. 🧑‍💻
=> feat: add finish early button

.gitignore, workspaces/web/package.json, workspaces/web/percypress.sh
=> ci(package.json): fix cypress on forks

workspaces/web/src/client.js, workspaces/web/src/components/NavBar.svelte, workspaces/web/src/components/SponsorButton.svelte
=> feat(navbar): added sponsor button

workspaces/lluis/Content.svelte, workspaces/lluis/package-lock.json, workspaces/web/src/components/MarkDownPage.svelte, workspaces/web/src/mystyles.scss, workspaces/web/src/routes/course/[courseName]/index.svelte, workspaces/web/src/routes/devtools.svelte
Please let me know if I missed anything, this is my first time using Svelte.
=> Add Content component (resolve #853)

workspaces/web/cypress/support/commands.js, workspaces/web/package.json, yarn.lock
=> chore: use cy-tkey-screenshot for translation screnshots

workspaces/web/cypress.json
=> ci(cypress): enable test retries

Pipfile, Pipfile.lock, course/management/commands/exportcourse.py, course/test_exportcourse.py, workspaces/liblili2json/liblili2json.egg-info/SOURCES.txt, workspaces/liblili2json/liblili2json.egg-info/requires.txt, workspaces/liblili2json/liblili2json/__init__.py, workspaces/liblili2json/liblili2json/types.py, workspaces/liblili2json/tests/fakes.py, workspaces/liblili2json/tests/test_liblili2json.py, workspaces/web/src/courses/spanish-from-english/challenges/adjectives.json, workspaces/web/src/courses/spanish-from-english/challenges/animals.json, workspaces/web/src/courses/spanish-from-english/challenges/clothes.json, workspaces/web/src/courses/spanish-from-english/challenges/continuous.json, workspaces/web/src/courses/spanish-from-english/challenges/food.json, workspaces/web/src/courses/spanish-from-english/challenges/nature.json, workspaces/web/src/courses/spanish-from-english/challenges/phrases.json, workspaces/web/src/courses/spanish-from-english/challenges/plurals.json, workspaces/web/src/courses/spanish-from-english/challenges/preferences.json, workspaces/web/src/courses/spanish-from-english/challenges/professions.json, workspaces/web/src/courses/spanish-from-english/challenges/ser-estar.json, workspaces/web/src/courses/spanish-from-english/challenges/verb-plurals.json, workspaces/web/src/courses/spanish-from-english/challenges/verbs.json
=> refactor: use liblili2json to export skills

README.md, docs/index.md
=> docs: link dev.to article in docs

workspaces/liblili2json/liblili2json/__init__.py, workspaces/liblili2json/liblili2json/challenge_types.py, workspaces/liblili2json/liblili2json/dictionary.py, workspaces/liblili2json/liblili2json/utils.py, workspaces/liblili2json/tests/test_liblili2json.py
=> Improve liblili2json

course/management/commands/exportcourse.py, course/test_exportcourse.py, workspaces/liblili2json/liblili2json.egg-info/SOURCES.txt, workspaces/liblili2json/liblili2json.egg-info/requires.txt, workspaces/liblili2json/liblili2json/__init__.py, workspaces/liblili2json/liblili2json/challenge_types.py, workspaces/liblili2json/liblili2json/course.py, workspaces/liblili2json/liblili2json/export.py, workspaces/liblili2json/liblili2json/types.py, workspaces/liblili2json/poetry.lock, workspaces/liblili2json/pyproject.toml, workspaces/liblili2json/tests/fakes.py, workspaces/liblili2json/tests/test_export.py
=> use liblili2json to write files

Pipfile, Pipfile.lock, courses/french-from-english/course.yaml, courses/french-from-english/modules/basics/skills/hello.yaml, workspaces/liblili2json/liblili2json/export.py, workspaces/liblili2json/liblili2json/yaml.py, workspaces/liblili2json/poetry.lock, workspaces/liblili2json/pyproject.toml, workspaces/liblili2json/tests/fixtures/fake_course/basics/module.yaml, workspaces/liblili2json/tests/fixtures/fake_course/basics/skills/hello.yaml, workspaces/liblili2json/tests/fixtures/fake_course/course.yaml, workspaces/liblili2json/tests/snapshots/snap_test_integration.py, workspaces/liblili2json/tests/test_export.py, workspaces/liblili2json/tests/test_integration.py, workspaces/liblili2json/tests/test_yaml.py
=> Support exporting YAML courses

workspaces/librelingo_tools/librelingo_tools/cli.py, workspaces/librelingo_tools/librelingo_tools/export.py, workspaces/librelingo_tools/tests/test_cli.py, workspaces/librelingo_tools/tests/test_export.py
=> feat(tools): add --dry-run

.gitignore, README.md
=> fix(readme): improve web app documentation

README.md
=> docs(readme): improve milestones

README.md, docs/translation.md
=> docs(readme): improve "Become a contributor" section

README.md
=> docs(readme): improve layout of"Become a contributor"

docs/creating-courses.md
=> docs: add readme about editing courses

README.md, docs/courses/README.md, docs/courses/editing-courses.md, docs/index.md
While reading the docs of the project, I found a couple of minor mistakes and thought I'd fix them while I'm at it.
=> docs: improve spelling and formatting

workspaces/librelingo_tools/librelingo_tools/yaml_loader.py, workspaces/librelingo_tools/tests/test_integration.py, workspaces/librelingo_tools/tests/test_yaml_loader.py
=> Support mini dictionary

package.json, scripts/exportAllYamlCourses.sh, scripts/exportYamlCourse.sh, workspaces/librelingo_tools/librelingo_tools/challenge_types.py, workspaces/librelingo_tools/librelingo_tools/yaml_loader.py, workspaces/librelingo_tools/tests/snapshots/snap_test_integration.py, workspaces/librelingo_tools/tests/test_challenges.py, workspaces/librelingo_tools/tests/test_yaml_loader.py, workspaces/web/src/courses/french-from-english/challenges/hello.json
=> feat(tools): improve error messages

workspaces/librelingo_tools/librelingo_tools/data_types.py, workspaces/librelingo_tools/librelingo_tools/yaml_loader.py, workspaces/librelingo_tools/tests/fakes.py, workspaces/librelingo_tools/tests/snapshots/snap_test_integration.py, workspaces/librelingo_tools/tests/test_yaml_loader.py, workspaces/web/src/courses/french-from-english/challenges/hello.json
=> feat(tools): add "dictionary" to Skill() type

workspaces/librelingo_tools/librelingo_tools/data_types.py, workspaces/librelingo_tools/librelingo_tools/dictionary.py, workspaces/librelingo_tools/librelingo_tools/yaml_loader.py, workspaces/librelingo_tools/tests/test_librelingo_tools.py, workspaces/librelingo_tools/tests/test_yaml_loader.py
=> Small refactors

workspaces/librelingo_tools/librelingo_tools/yaml_loader.py, workspaces/librelingo_tools/tests/test_yaml_loader.py
=> fix(tools): include definitions from new words correctly

courses/french-from-english/basics/skills/hello.yaml, courses/german-from-english/basics/skills/hello.yaml, workspaces/librelingo_tools/librelingo_tools/dictionary.py, workspaces/librelingo_tools/tests/fakes.py, workspaces/librelingo_tools/tests/fixtures/fake_course/basics/skills/hello.yaml, workspaces/librelingo_tools/tests/snapshots/snap_test_integration.py, workspaces/librelingo_tools/tests/test_challenges.py, workspaces/librelingo_tools/tests/test_librelingo_tools.py, workspaces/librelingo_tools/tests/test_yaml_loader.py, workspaces/web/src/courses/french-from-english/challenges/hello.json, workspaces/web/src/courses/german-from-english/challenges/hello.json
=> feat(tools): force words to have definitions

apps/answer-corrector/package.json, apps/lluis/package.json, apps/web/package.json, package.json, yarn.lock
=> Set up semantic release

jest.config.js
=> chore: change 'tsConfig' to 'tsconfig' in jest.config.js

.semaphore/pipeline_3.yml
set up semantic-release for all packages that are not private
fixes #1081
_..._
=> fix(web): fix package release

apps/web/src/components/ChipsChallenge/index.svelte
Based off of  HugoLiconV's code. Removed sortable code and add onclick code.
I also changed the cursor when hovering over a button so the user knows to click.
It was a bit odd with the cursor never changing when using padding so i switched
to margin and increased the horizontal margin a bit.
_..._
=> feat(web): click to move words in ChipsChallenge

apps/librelingo_tools/librelingo_tools/__init__.py, apps/librelingo_tools/pyproject.toml
=> feat(tools): release a new version of librelingo-tools

docs/CONTRIBUTING.md, mkdocs.yml
=> docs: remove references to django

mkdocs.yml, package.json, poetry.lock, pyproject.toml
=> docs: set up mkdocs material

apps/librelingo_fakes/README.md, apps/librelingo_fakes/librelingo_fakes/__init__.py, apps/librelingo_fakes/pyproject.toml, apps/librelingo_utils/README.md, apps/librelingo_utils/librelingo_utils/__init__.py, apps/librelingo_utils/poetry.lock, apps/librelingo_utils/pyproject.toml, apps/librelingo_yaml_loader/README.md, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/pyproject.toml
=> docs(fakes): add missing README

README.md, apps/web/src/routes/development.svelte, docs/CONTRIBUTING.md, docs/index.md, mkdocs.yml, poetry.lock, pyproject.toml
=> documentation updates

.semaphore/semaphore.yml, apps/librelingo_yaml_loader/README.md, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, scripts/updatePypiReadmeFiles.sh, scripts/verifyPypiReadmeFiles.sh
=> ci: verify that PyPi README files are up to date

.eslintrc.js, apps/web/cypress/plugins/index.js, apps/web/src/components/ChallengeScreen.svelte, apps/web/src/components/GitHubButton.svelte, apps/web/src/components/SkillCard/index.svelte, apps/web/src/db/db.js, apps/web/src/db/live.js, apps/web/src/routes/devtools.svelte, apps/web/src/routes/login.svelte, apps/web/src/routes/sign-up-success.svelte, apps/web/src/routes/sign-up.svelte, package.json, yarn.lock
=> chore: improve eslint config

apps/web/cypress/integration/cards.feature, apps/web/src/components/ChallengePanel.svelte
=> feat(web): remove <ChallengePanel /> animation

.semaphore/semaphore.yml, apps/web/cypress/integration/cards.feature, apps/web/package.json, apps/web/src/components/ChallengePanel.svelte, package.json, yarn.lock
=> chore: update some dependencies

apps/lluis/ButtonLink.svelte, apps/web/package.json, apps/web/src/components/FanfareScreen.svelte, apps/web/src/components/GitHubButton.svelte, apps/web/src/components/NavBar.svelte, apps/web/src/components/SkillCard/Buttons.svelte, apps/web/src/components/SponsorButton.svelte, apps/web/src/components/TwitterButton.svelte, apps/web/src/routes/index.svelte, apps/web/src/routes/sign-up-success.svelte
=> refactor(lluis): extract <ButtonLink />

apps/lluis/NavBar.svelte, apps/web/src/components/NavBar.svelte, apps/web/src/mystyles.scss
=> feat(lluis): add <NavBar />

apps/lluis/NavBar.svelte, apps/web/src/components/NavBar.svelte
=> Implement custom navbqr

apps/lluis/ButtonSet.svelte, apps/lluis/Logo.svelte, apps/lluis/NavBar.svelte, apps/web/src/components/FanfareScreen.svelte, apps/web/src/components/MarkDownPage.svelte, apps/web/src/components/NavBar.svelte, apps/web/src/mystyles.scss, apps/web/src/routes/course/[courseName]/index.svelte, apps/web/src/routes/course/[courseName]/skill/[id].svelte, apps/web/src/routes/dev-typography.svelte, apps/web/src/routes/devtools.svelte, apps/web/src/routes/login.svelte, apps/web/src/routes/sign-up-success.svelte, apps/web/src/routes/sign-up.svelte
=> Implement custom navbar

courses/parsig-from-english/basics/module.yaml, courses/parsig-from-english/basics/skills/hello.yaml, courses/parsig-from-english/course.yaml
Add a new course for Middle Persian, aka Parsig or Pahlavi.
=> Add first Middle Persian lesson

apps/librelingo_audios/poetry.lock, apps/librelingo_fakes/poetry.lock, apps/librelingo_json_export/README.md, apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/librelingo_json_export/challenge_types.py, apps/librelingo_json_export/librelingo_json_export/challenges.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_json_export/tests/test_challenges.py, apps/librelingo_json_export/tests/test_export.py, apps/librelingo_types/README.md, apps/librelingo_types/librelingo_types/__init__.py, apps/librelingo_types/librelingo_types/data_types.py, apps/librelingo_types/pyproject.toml, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, apps/librelingo_yaml_loader/poetry.lock, apps/librelingo_yaml_loader/pyproject.toml, apps/librelingo_yaml_loader/tests/test_yaml_loader.py, apps/web/src/courses/bangla-from-english/challenges/animals.json, apps/web/src/courses/bangla-from-english/challenges/clothes.json, apps/web/src/courses/bangla-from-english/challenges/food.json, apps/web/src/courses/parsig-from-english/challenges/basic-1.json, courses/bangla-from-english/course.yaml, courses/parsig-from-english/course.yaml, poetry.lock
=> Add option to disable audio files

docs/courses/editing-courses.md
I think this shouldn't be "--ammend" just "--amend" could confuse a bit when following the Setup.
=> small typo fix

README.md
=> docs(readme): update references to python packages

apps/librelingo_fakes/librelingo_fakes/__init__.py, apps/librelingo_fakes/librelingo_fakes/fakes.py, apps/librelingo_fakes/poetry.lock, apps/librelingo_fakes/pyproject.toml, apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_json_export/tests/fixtures/fake_course/course.yaml, apps/librelingo_types/README.md, apps/librelingo_types/librelingo_types/__init__.py, apps/librelingo_types/librelingo_types/data_types.py, apps/librelingo_types/poetry.lock, apps/librelingo_types/pyproject.toml, apps/librelingo_utils/librelingo_utils/__init__.py, apps/librelingo_utils/poetry.lock, apps/librelingo_utils/pyproject.toml, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, apps/librelingo_yaml_loader/poetry.lock, apps/librelingo_yaml_loader/pyproject.toml, apps/librelingo_yaml_loader/tests/fixtures/fake_course/course.yaml, apps/librelingo_yaml_loader/tests/test_yaml_loader.py, poetry.lock
=> draft: feat: add repository url to Course()

.semaphore/semaphore.yml, apps/librelingo_audios/librelingo_audios/__init__.py, apps/librelingo_audios/tests/test_list_missing_audios.py, apps/librelingo_fakes/librelingo_fakes/__init__.py, apps/librelingo_fakes/librelingo_fakes/fakes.py, apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/librelingo_json_export/challenge_types.py, apps/librelingo_json_export/librelingo_json_export/challenges.py, apps/librelingo_json_export/librelingo_json_export/cli.py, apps/librelingo_json_export/librelingo_json_export/course.py, apps/librelingo_json_export/librelingo_json_export/dictionary.py, apps/librelingo_json_export/librelingo_json_export/export.py, apps/librelingo_json_export/librelingo_json_export/module.py, apps/librelingo_json_export/librelingo_json_export/skills.py, apps/librelingo_json_export/tests/snapshots/snap_test_integration.py, apps/librelingo_json_export/tests/test_challenges.py, apps/librelingo_json_export/tests/test_cli.py, apps/librelingo_json_export/tests/test_export.py, apps/librelingo_json_export/tests/test_integration.py, apps/librelingo_types/README.md, apps/librelingo_types/librelingo_types/__init__.py, apps/librelingo_types/librelingo_types/data_types.py, apps/librelingo_utils/librelingo_utils/__init__.py, apps/librelingo_utils/librelingo_utils/utils.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, apps/librelingo_yaml_loader/tests/test_yaml_loader.py, poetry.lock, pyproject.toml
=> style: install black for auto code formatting for Python

.semaphore/semaphore.yml, poetry.lock, pyproject.toml
=> chore(ci): run mypy in the pipeline

.semaphore/semaphore.yml, apps/librelingo_audios/librelingo_audios/__init__.py, apps/librelingo_audios/pyproject.toml, apps/librelingo_fakes/librelingo_fakes/__init__.py, apps/librelingo_fakes/pyproject.toml, apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_types/librelingo_types/__init__.py, apps/librelingo_types/poetry.lock, apps/librelingo_types/pyproject.toml, apps/librelingo_utils/librelingo_utils/__init__.py, apps/librelingo_utils/pyproject.toml, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/pyproject.toml, poetry.lock, pyproject.toml
=> chore: make python package compatible with Python 3.8

apps/librelingo_audios/poetry.lock, apps/librelingo_fakes/poetry.lock, apps/librelingo_utils/poetry.lock, apps/librelingo_yaml_loader/poetry.lock
=> chore: fix poetry.lock files

apps/librelingo_audios/poetry.lock, apps/librelingo_fakes/poetry.lock, apps/librelingo_utils/poetry.lock, apps/librelingo_yaml_loader/poetry.lock, poetry.lock
=> Fix readmes

apps/web/src/components/MarkDownPage.svelte
=> fix: fix markdown loading

apps/web/src/components/ChallengeScreen.svelte, apps/web/src/routes/course/[courseName]/skill/[id]/index.svelte
=> test(web): fix testChallenge feature in static build

.semaphore/semaphore.yml
=> ci: fix static build on main

.semaphore/semaphore.yml, apps/web/package.json, apps/web/src/components/ChallengeScreen.svelte, apps/web/src/components/MarkDownPage.svelte, apps/web/src/routes/about.svelte, apps/web/src/routes/devtools.svelte, apps/web/src/routes/index.svelte
=> ci: run cypress on a statically built page

apps/librelingo_fakes/librelingo_fakes/fakes.py, apps/librelingo_json_export/librelingo_json_export/challenge_types.py, apps/librelingo_json_export/librelingo_json_export/dictionary.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_json_export/tests/test_challenges.py, apps/librelingo_json_export/tests/test_export.py, apps/librelingo_utils/README.md, apps/librelingo_utils/librelingo_utils/utils.py, apps/librelingo_utils/pyproject.toml, poetry.lock
Implements the feature described in #1450.
Note that this does not make any changes to the chips (they will still split on spaces). Personally, I don't see the value in joined chips, but if it's something you're set on, it can always be implemented separately.
=> feat: Add support for single words/terms with spaces in them

apps/web/cypress/integration/common/everything_looks_correct.js, apps/web/cypress/support/commands.js, apps/web/cypress/support/index.js, apps/web/package.json, apps/web/percypress.sh, yarn.lock
=> chore: temporarily disable percy

docs/courses/skill.md
Documents the `Mini-dictionary` in general, including information on the new multi-word terms feature.
=> Document Mini-dictionary

.semaphore/semaphore.yml, apps/web/cypress/integration/common/everything_looks_correct.js, apps/web/cypress/support/commands.js, apps/web/cypress/support/index.js, apps/web/package.json, apps/web/percypress.sh, yarn.lock
=> chore(ci): re-enable percy

apps/web/cypress/integration/chips.feature, apps/web/cypress/integration/common/everything_looks_correct.js, apps/web/cypress/integration/optionSelection.feature, apps/web/src/components/OptionCard.svelte
=> test: make sure Percy tests are not flaky

apps/web/cypress/integration/optionSelection.feature, apps/web/src/components/OptionChallenge/index.svelte
Brings the options challenges in line with other challenge types by giving the user feedback on the correct choice when they select an incorrect answer.
=> feat: display the correct answer on options challenges

apps/web/cypress/integration/common/everything_looks_correct.js, apps/web/src/components/DeckChallenge/index.svelte, apps/web/src/components/OptionChallenge/index.svelte
=> test: fix more percy flakiness

apps/web/cypress/integration/common/everything_looks_correct.js, apps/web/src/components/OptionCard.svelte, apps/web/src/components/ShortInputChallenge.svelte
=> chore: fix the remaining percy flakiness

apps/web/cypress/integration/common/everything_looks_correct.js, apps/web/src/components/OptionCard.svelte
=> chore: fix flaky visual test on mobile

poetry.lock, pyproject.toml, pytest.ini
=> chore: enable develop mode for monorepo packages in poetry

apps/librelingo_audios/librelingo_audios/functions.py, apps/librelingo_audios/librelingo_audios/update_audios.py, apps/librelingo_audios/tests/conftest.py, apps/librelingo_audios/tests/test_list_missing_audios.py, apps/librelingo_audios/tests/test_update_audios.py
=> Refactors for audio fetcher

courses/german-from-english/basics/skills/hello.md, courses/german-from-english/basics/skills/plurals.md
fixed formatting etc of markdown files
=> fix: formatting of .md files english-german

apps/lluis/Panel.svelte, apps/web/src/components/ChallengePanel.svelte, apps/web/src/mystyles.scss
=> feat(lluis): add <Panel /> component

apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_types/README.md, apps/librelingo_types/librelingo_types/__init__.py, apps/librelingo_types/librelingo_types/data_types.py, apps/librelingo_types/pyproject.toml, apps/librelingo_yaml_loader/README.md, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/_spelling.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, apps/librelingo_yaml_loader/poetry.lock, apps/librelingo_yaml_loader/pydoc-markdown.yml, apps/librelingo_yaml_loader/pyproject.toml, apps/librelingo_yaml_loader/tests/test_yaml_loader.py, courses/german-from-english/course.yaml, docs/courses/course.md, poetry.lock
=> feat(yaml_loader): add hunspell spell checking

apps/web/scripts/installExternalCourse.sh, apps/web/scripts/installExternalCourses.sh
Update installExternalCourses.sh
_..._
=> feat: import german course from external repo

apps/web/src/components/MarkDownPage.svelte, apps/web/src/mystyles.scss
With this implementation "About" page looks like:
fixes https://github.com/kantord/LibreLingo/issues/1514
_..._
=> feat: highlight links on the markdown page

apps/web/package.json, yarn.lock
fixes https://github.com/kantord/LibreLingo/issues/1662
_..._
=> chore(deps): update-remark-rehype to v8.1.0

apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
=> refactor: comment fix

apps/librelingo_audios/librelingo_audios/__init__.py, apps/librelingo_audios/pyproject.toml, apps/librelingo_fakes/librelingo_fakes/__init__.py, apps/librelingo_fakes/pyproject.toml, apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_types/librelingo_types/__init__.py, apps/librelingo_types/pyproject.toml, apps/librelingo_utils/librelingo_utils/__init__.py, apps/librelingo_utils/poetry.lock, apps/librelingo_utils/pyproject.toml, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/poetry.lock, apps/librelingo_yaml_loader/pyproject.toml, poetry.lock
=> fix(utils): fix version of 'regex'

.gitignore, apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/librelingo_json_export/dictionary.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_utils/README.md, apps/librelingo_utils/librelingo_utils/__init__.py, apps/librelingo_utils/librelingo_utils/utils.py, apps/librelingo_utils/pyproject.toml
=> Get Basque course export speed from 270s to 31s

apps/librelingo_json_export/README.md, apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/librelingo_json_export/cli.py, apps/librelingo_json_export/poetry.lock, apps/librelingo_json_export/pyproject.toml, apps/librelingo_json_export/tests/test_cli.py, poetry.lock, scripts/exportYamlCourse.sh
=> refactor: run export script from main venv instead of app-specific

docs/courses/README.md
=> docs: fix typo in courses/README.md

scripts/exportYamlCourse.sh
=> fix the paths for exporting yaml course fixing #1801

docs/courses/README.md
=> update links to course sources fixing #1794

apps/librelingo_json_export/README.md, apps/librelingo_json_export/pydoc-markdown.yml, apps/librelingo_json_export/pyproject.toml
=> docs: temorarily ignore cli module in librelingo_json_export

docs/index.md
=> update setup instructions fixing #1799

.semaphore/pipeline_2.yml, .semaphore/pipeline_3.yml, .semaphore/semaphore.yml, package.json, yarn.lock
=> build: update semantic-release

apps/web/cypress/integration/shortInput.feature, apps/web/package.json, yarn.lock
=> build: update cypress

.semaphore/semaphore.yml, poetry.lock, pylintrc, pyproject.toml
=> chore: set up pylint

.semaphore/semaphore.yml, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
demo for issue #1889
If this looks good to you I can add more examples and convert the existing documents to doctests
=> run doctest, add first doctest #1889

apps/librelingo_fakes/librelingo_fakes/fakes.py, apps/librelingo_json_export/tests/test_export.py, apps/librelingo_types/README.md, apps/librelingo_types/librelingo_types/data_types.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, apps/librelingo_yaml_loader/tests/test_yaml_loader.py
Adding course_dir to the Course object and filename to both the Module and the Skill objects.
fixes #1852
=> Addfilenames #1852

apps/librelingo_audios/librelingo_audios/update_audios.py, apps/librelingo_fakes/librelingo_fakes/fakes.py, apps/librelingo_json_export/librelingo_json_export/dictionary.py, apps/librelingo_json_export/librelingo_json_export/export.py, apps/librelingo_json_export/librelingo_json_export/module.py, apps/librelingo_json_export/tests/test_cli.py, apps/librelingo_json_export/tests/test_export.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, apps/librelingo_yaml_loader/tests/test_yaml_loader.py, pylintrc
=> Pylint use f string

apps/librelingo_json_export/librelingo_json_export/challenges.py, pylintrc
=> Remove unused wildcard imports

apps/librelingo_audios/tests/test_update_audios.py, pylintrc
=> fix pointless-statement, correct test calls #1896

apps/librelingo_audios/librelingo_audios/update_audios.py, apps/librelingo_audios/tests/test_update_audios.py, apps/librelingo_json_export/librelingo_json_export/challenges.py, apps/librelingo_json_export/tests/test_challenges.py, apps/librelingo_json_export/tests/test_export.py, pylintrc
=> remove unused-import #1898

apps/librelingo_json_export/librelingo_json_export/export.py
=> f-string needs and f

apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, pylintrc
=> fix bare-except  #1899

apps/librelingo_types/README.md, apps/librelingo_types/librelingo_types/data_types.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
progress on #1889
There are a few more remaining cases, but they need some setup so I am not sure they should be converted.
=> Convert text documentation to executable documentation for #1889

apps/librelingo_json_export/tests/test_export.py, pylintrc
Removed unused-variables from pylintrc.
fixes #1897
_..._
=> Remove unused variables

pylintrc
fixes #1930
Apparently, This needs a second commit. I need to either import the rule or remove it. Please let me know if I need to make any changes. 
_..._
=> enable deprecated-pragma

package.json, yarn.lock
This reverts commit 4c7e07ca6f63b1f2e72f39f6db70955028c69765.
revert: revert "revert: revert "feat: update basque course""
This reverts commit f14e0d86d8cfd7fd66437d8b4faaba3c79c6be34.
_..._
=> fix: fix librelingo-tools deployment

apps/librelingo_json_export/tests/test_challenges_clean_word.py, apps/librelingo_json_export/tests/test_challenges_get_cards_challenge.py, apps/librelingo_json_export/tests/test_challenges_get_chips_challenge.py, apps/librelingo_json_export/tests/test_challenges_get_options_challenge.py, apps/librelingo_json_export/tests/test_challenges_get_short_input_challenge.py, apps/librelingo_json_export/tests/test_challenges_listening_challenge.py
I parametrized some of the tests.
=> refactor(tests): use @pytest.mark.parametrize

apps/librelingo-standalone-server/build.sh, apps/web/scripts/fetchPhoto.sh, apps/web/scripts/fetchPhotos.sh, apps/web/scripts/installExternalCourse.sh, scripts/exportAllYamlCourses.sh, scripts/exportYamlCourse.sh, scripts/updateAudioForAllYamlCourses.sh, scripts/updateAudioForYamlCourse.sh, scripts/updatePypiReadmeFiles.sh, scripts/verifyPypiReadmeFiles.sh, scripts/verifyTestCourseJsonFiles.sh
I did some basic linting of the shell scripts.
I think that it might be a good idea to:
- add `set -euo pipefail` at the beginning of every 'sh' file,
- add `shellcheck` into CI.
=> fix: avoid potential bugs

apps/librelingo_yaml_loader/README.md
=> chore: update python dependencies

apps/librelingo_yaml_loader/README.md, apps/robots.txt/robots.txt
=> chore: add robots.txt

.github/workflows/check_shell_scripts.yml, .semaphore/semaphore.yml
this test has been failing for a long time, seemingly for no reason.
=> docs: remove pypi readme file test

apps/lluis/NavBar/NavBarButton.svelte, apps/web/cypress/integration/chips.feature, apps/web/cypress/integration/common/button_new_tab.js, apps/web/cypress/integration/coursePage.feature, apps/web/cypress/integration/feedbackButton.feature, apps/web/src/components/NavBar.svelte, apps/web/src/courses/test/courseData.json, apps/web/src/routes/course/[courseName]/index.svelte, apps/web/src/routes/course/[courseName]/skill/[id]/index.svelte, courses/test/course.yaml
=> feat: add feedback button that leads to the repository of the course

apps/tools/tests/test_test_course.py
=> Test with test course

apps/docker/Dockerfile, apps/docker/README.md, apps/docker/docker-compose.yml, apps/docker/docker-entrypoint.sh, apps/docker/start.sh
Changes:
- Made the image smaller
- Made the dockerfile much neater
- Simplified installation of packages in dockerfile
- Updated readme
- Allow for the importing of multiple courses and courses can have whatever name rather than just having "your-course"
- Moved image name on hub.docker.com from cutthroat78/librelingo to librelingo/librelingo to make an easier image name to remember
=> Changed Docker image from nodejs to Arch Linux

apps/web/cypress/integration/gistPreview.feature, apps/web/cypress/integration/optionSelection.feature, apps/web/cypress/support/index.js, apps/web/src/client.js, apps/web/src/course-client/index.ts, apps/web/src/mocks/handlers.js, docs/index.md
This reverts commit 6d222c69476abf42d4d20e8f39f13cc181069865.
=> revert: revert "chore: remove commented-out code (#2083)"

apps/web/src/routes/course/[courseName]/skill/[skillName]/introduction.svelte
=> Adds "go back" button to course introduction page

config/courses.json
* feat: enable portuguese course
* fix: temporarily disable french course
=> fix: disable french course in the dev tools

apps/librelingo_json_export/librelingo_json_export/__init__.py, apps/librelingo_json_export/pyproject.toml, apps/librelingo_yaml_loader/librelingo_yaml_loader/__init__.py, apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, apps/librelingo_yaml_loader/pyproject.toml
related (but does not completely fix) https://github.com/LibreLingo/LibreLingo/issues/2314
=> perf(yaml-loader): improve performance of loading YAML

apps/librelingo_json_export/librelingo_json_export/dictionary.py, apps/librelingo_json_export/tests/test_challenges_define_word.py, apps/librelingo_utils/librelingo_utils/utils.py, apps/librelingo_utils/pyproject.toml, apps/librelingo_utils/tests/test_get_words_from_phrase.py, apps/tools/tests/fixtures/e2/basics/skills/hello.yaml, apps/tools/tests/test_real_courses.py
=> fix(utils): don't return punctuation as words

apps/librelingo_json_export/tests/test_challenges_get_chips_challenge.py, apps/librelingo_utils/librelingo_utils/utils.py, apps/librelingo_utils/tests/test_get_words_from_phrase.py
=> fix(utils): fix issue when phrase has both ' and ,

apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py, pytest.ini
=> Issue-2499: fix 2 instances of lines that are too long

apps/librelingo_json_export/librelingo_json_export/dictionary.py, apps/librelingo_json_export/tests/test_challenges_define_word.py
use clean_word in error message
=> feat: show missing dict words without punctuation

docs/courses/README.md, docs/courses/challenge.md, docs/courses/course.md, docs/courses/creating-courses.md, docs/courses/editing-courses.md, docs/courses/module.md, docs/courses/skill.md, docs/creating_a_python_language_learning_app_using_librelingo_courses.md
While reading through the courses-documentation, I decided to fix some typos and punctuation errors I found and restructure some sentences to make them more easily understandable.
=> Fix typos and punctuation in documentation

apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py
Extra pylint fix to get CI to pass for #2587
=> Fix pylint error

.github/workflows/python.yml
=> ci: update ubuntu version for tests

.gitignore, apps/web/cypress/integration/cancelButton.feature, apps/web/src/components/ChallengeScreen.svelte, apps/web/src/courses/test-2/challenges/animals.json, apps/web/src/courses/test-2/courseData.json, apps/web/src/routes/devtools.svelte, courses/test-2/basics/module.yaml, courses/test-2/basics/skills/animals.yaml, courses/test-2/course.yaml
=> Fix cancel session leads to wrong screen

docs/index.md
=> docs: document how to keep local deps up to date

.github/FUNDING.yml, README.md, apps/web/src/components/SponsorButton.svelte
=> feat: remove sponsor links

docs/teaching_philosophy.md
This pull request is a follow-up to [issue #1496](https://github.com/LibreLingo/LibreLingo/issues/1496), which discusses the lack of non-technical documentation on the teaching philosophy of LibreLingo. This issue has been stale for almost two years, but is still open. I created a piece of documentation with the points discussed by Daniel. Please let me know if any changes need to be made, or if more information should be included. I'm happy to expand it in any way the community sees fit.
=> Create teaching philosophy documentation
